version: "3.9"
services:
  api:
    build:
      context: .
    volumes:
      - '.:/app'
    entrypoint: [ "sh", "./start.sh" ]
    ports:
      - "1323:1323"
    environment:
      - mongousername=mongoadmin
      - mongopassword=secret
      - mode=local
    depends_on:
      - db
      - worker
  worker:
    build:
      context: .
    volumes:
      - '.:/app'
    entrypoint: [ "sh", "./start.sh", "worker" ]
    environment:
      - mongousername=mongoadmin
      - mongopassword=secret
      - mode=local
    depends_on:
      - db
    logging:
      driver: none # Change This If You Want To Read Logs
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - api_db_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
volumes:
  api_db_data:
    driver: local
