version: "3.9"
services:
  backend:
    build:
      context: .
    volumes:
      - '.:/app'
    entrypoint: [ "sh","./init.sh" ]
    ports:
      - "1323:1323"
    environment:
      - mongousername=mongoadmin
      - mongopassword=secret
      - mode=local
    depends_on:
      - db
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
