apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-api
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jonathan_wright@hotmail.com
    privateKeySecretRef:
      name: letsencrypt-api
    solvers:
      - http01:
          ingress:
            class:  nginx